apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-traffic-from-silotenanta-namespace
spec:
  selector:
    matchLabels:
      app: web
  action: DENY
  rules:
  - from:
    - source:
       namespaces: ["silotenanta"]