FROM public.ecr.aws/bitnami/node:16.5.0 AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn build product

FROM public.ecr.aws/bitnami/node:16.5.0
WORKDIR /app
COPY --from=build /app ./
EXPOSE 3005
CMD ["npm", "run", "start:product"]
