apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-management
  template:
    metadata:
      labels:
        app: tenant-management
    spec:
      containers:
        - name: tenant-management
          image: public.ecr.aws/o2b5n0j5/eks-saas-tenant-management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: "http"
          env:
            - name: AWS_REGION
              value: "us-west-2"
            - name: COGNITO_USER_POOL_ID
              value: "us-west-2_aw33YGjZo"
            - name: COGNITO_CLIENT_ID
              value: "5m7i2urrjv61dou5lmm7ege6mp"
            - name: COGNITO_REGION
              value: "us-west-2"
            - name: TENANT_TABLE_NAME
              value: "Tenants-20220725142746"
            - name: AUTH_TENANT_TABLE_NAME
              value: "AuthInfo-20220725142746"
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-management-service
spec:
  selector:
    app: tenant-management
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant-management-service-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: a6827acb0d6ef4172b966aa6ba3da833-2faefb68832aa130.elb.us-west-2.amazonaws.com
      http:
        paths:
          - backend:
              service:
                name: tenant-management-service
                port:
                  number: 80
            path: /api/tenants
            pathType: Prefix
