FROM public.ecr.aws/bitnami/node:18.18.0 AS build
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN corepack enable
RUN yarn set version stable
RUN yarn install
COPY . .
RUN yarn build user-management

FROM public.ecr.aws/bitnami/node:18.18.0
WORKDIR /app
COPY --from=build /app ./
CMD ["npm", "run", "start", "user-management"]
