FROM public.ecr.aws/bitnami/node:16.13.1 AS build
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn
COPY . .
RUN yarn build tenant-management

FROM public.ecr.aws/bitnami/node:16.13.1
WORKDIR /app
COPY --from=build /app ./
EXPOSE 3001
CMD ["npm", "run", "start", "tenant-management"]
