FROM public.ecr.aws/bitnami/node:16.16.0 AS build
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn
COPY . .
RUN yarn build product

FROM public.ecr.aws/bitnami/node:16.16.0
WORKDIR /app
COPY --from=build /app ./
EXPOSE 3005
CMD ["npm", "run", "start", "product"]
