FROM public.ecr.aws/bitnami/node:16.16.0 AS build
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn
COPY . .
RUN yarn build user-management

FROM public.ecr.aws/bitnami/node:16.16.0
WORKDIR /app
COPY --from=build /app ./
CMD ["npm", "run", "start", "user-management"]
