apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: public.ecr.aws/o2b5n0j5/eks-saas-order:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
              name: "http"
          env:
            - name: AWS_REGION
              value: "us-west-2"
            - name: IAM_ROLE_ARN
              value: ""
            - name: COGNITO_USER_POOL_ID
              value: "us-west-2_pwhlbgL09"
            - name: COGNITO_CLIENT_ID
              value: "t278btubmqb1hgan2afaut02g"
            - name: COGNITO_REGION
              value: "us-west-2"
            - name: ORDER_TABLE_NAME
              value: "Orders-Pooled-20220725142746"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3010
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-service-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: a6827acb0d6ef4172b966aa6ba3da833-2faefb68832aa130.elb.us-west-2.amazonaws.com
      http:
        paths:
          - backend:
              service:
                name: order-service
                port:
                  number: 80
            path: /app/api/orders
            pathType: Prefix
