FROM public.ecr.aws/bitnami/node:16.5.0 AS build
WORKDIR /app
COPY package.json ./
RUN yarn
COPY . .
RUN yarn build tenant-registration

FROM public.ecr.aws/bitnami/node:16.5.0
WORKDIR /app
COPY --from=build /app ./
EXPOSE 3000
CMD ["npm", "run", "start:tr"]
