FROM public.ecr.aws/bitnami/node:16.5.0 AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn build tenant-registration

FROM public.ecr.aws/bitnami/node:16.5.0
WORKDIR /app
COPY --from=build /app ./
CMD ["npm", "run", "start:um"]
